services:
  mc:
    image: itzg/minecraft-server
    ports:
    #expose the Minecraft server port outside of container
    - "25565:25565"
    #add rcon port for command execution
    #login to RCON using
    #mcrcon -H ip_address -P 25575 -p password
    - "25575:25575"
    #If you want to use RCON make sure these options are set properly
    #enable-rcon=true
    #rcon.port=25575
    #rcon.password=your_password
    environment:
      #REQUIRED for all types
      EULA: "TRUE"
      MEMORY: "7G"
      TYPE: FORGE
      FORGE_VERSION: 47.1.0
      VERSION: 1.21.4
      ENABLE_ROLLING_LOGS: "true"
    volumes:
    #use a named, managed volume for data volume
    - ./data:/data

volumes:
  # eclared the named volume, but use default/local storage engine
  mc_forge: {}
