
["Fuel Items"]
	#Defines items that can be used as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	Boiler = [
        ["#minecraft:planks", 10], 
        ["minecraft:coal", 37], 
        ["minecraft:charcoal", 37], 
        ["#minecraft:logs_that_burn", 37], 
        ["minecraft:coal_block", 333], 
        ["minecraft:magma_block", 333], 
        ["minecraft:lava_bucket", 1000]
    ]
	Icebox = [
        ["minecraft:snowball", 10], 
        ["minecraft:clay_ball", 37], 
        ["minecraft:snow_block", 100], 
        ["minecraft:ice", 250], 
        ["minecraft:clay", 333], 
        ["minecraft:powder_snow_bucket", 100], 
        ["minecraft:packed_ice", 1000]
    ]
	#Negative values indicate cold fuel
	Hearth = [
        ["#minecraft:planks", 10], 
        ["minecraft:coal", 37], 
        ["minecraft:charcoal", 37], 
        ["#minecraft:logs_that_burn", 37], 
        ["minecraft:coal_block", 333], 
        ["minecraft:magma_block", 333], 
        ["minecraft:lava_bucket", 1000], 
        ["minecraft:snowball", -10], 
        ["minecraft:clay_ball", -37], 
        ["minecraft:snow_block", -100], 
        ["minecraft:ice", -250], 
        ["minecraft:clay", -333], 
        ["minecraft:powder_snow_bucket", -100], 
        ["minecraft:packed_ice", -1000]
    ]
	#Potions containing any of these effects will not be allowed in the hearth
	#Format: ["effect_id", "effect_id", ...etc]
	"Blacklisted Hearth Potions" = [
        "minecraft:instant_damage", 
        "minecraft:poison", 
        "minecraft:wither", 
        "minecraft:weakness", 
        "minecraft:mining_fatigue", 
        "minecraft:slowness"
    ]
	#If true, potions can be used as fuel in the hearth
	#This gives all players in range the potion effect
	"Allow Potions in Hearth" = true

["Soulspring Lamp"]
	#Defines items that the Soulspring Lamp can use as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	"Fuel Items" = [
        ["cold_sweat:soul_sprout", 4.0, "{}"]
    ]
	#Defines the dimensions that the Soulspring Lamp can be used in
	#Format: ["dimension-id-1", "dimension-id-2", ...etc]
	"Valid Dimensions" = ["minecraft:the_nether"]

[Insulation]
	#Defines the items that can be used for insulating armor in the Sewing Table
	#Format: [["item_id", cold, hot, "static", *nbt], ["item_id", amount, adapt-speed, "adaptive", *nbt], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#
	#Adaptive Insulation: 
	#"amount": The amount of insulation the item provides.
	#"adapt-speed": The speed at which the insulation adapts to the environment.
	#*"type": Optional. Either "static" or "adaptive". Defines the insulation type. Defaults to static.
	#*"nbt": Optional. If set, the item will only provide insulation if it has the specified NBT tag.
	#
	#Static Insulation: 
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	#*"type": Optional. Either "static" or "adaptive". Defines the insulation type. Defaults to static.
	#*"nbt": Optional. If set, the item will only provide insulation if it has the specified NBT tag.
	"Insulation Ingredients" = [
        #twilightforest
        ["twilightforest:arctic_fur", 2, 0], 
        ["twilightforest:alpha_yeti_fur", 4, 0], 
        #tinkers construct
        ["tconstruct:silky_cloth", 0, 1.5], 
        ["tinkers_thinking:gilded_silky_cloth", 0, 2], 
        #naturalist
        ["naturalist:bear_fur", 2, 0], 
        ["naturalist:reptile_hide", 0, 2], 
        #alex mobs
        ["alexsmobs:kangaroo_hide", 0, 1.5], 
        ["alexsmobs:shed_snake_skin", 0, 1.5], 
        ["alexsmobs:bison_fur", 2, 0], 
        ["alexsmobs:raccoon_tail", 2, 0], 
        ["alexsmobs:bear_fur", 2, 0], 
        ["alexsmobs:tarantula_hawk_wing_fragment", 0, 2], 
        #iceandfire
        ["iceandfire:troll_leather_forest", 1, 1], 
        ["iceandfire:troll_leather_mountain", 1, 1], 
        ["iceandfire:troll_leather_frost", 1, 1], 
        #farmersdelight
        ["mynethersdelight:hoglin_hide", 0, 2], 
        #minecraft
        ["minecraft:leather_helmet", 4.0, 4.0, "static", "{}"], 
        ["minecraft:leather_chestplate", 6.0, 6.0, "static", "{}"], 
        ["minecraft:leather_leggings", 5.0, 5.0, "static", "{}"], 
        ["minecraft:leather_boots", 4.0, 4.0, "static", "{}"], 
        ["minecraft:leather", 1.0, 1.0, "static", "{}"], 
        ["minecraft:white_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:orange_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:magenta_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:light_blue_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:yellow_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:lime_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:pink_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:gray_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:light_gray_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:cyan_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:purple_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:blue_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:brown_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:green_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:red_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:black_wool", 1.5, 0.0, "static", "{}"], 
        ["minecraft:rabbit_hide", 0.0, 1.5, "static", "{}"], 
        #cold_sweat
        ["cold_sweat:chameleon_molt", 2.0, 0.0085, "adaptive", "{}"], 
        ["cold_sweat:hoglin_hide", 0.0, 2.0, "static", "{}"], 
        ["cold_sweat:goat_fur", 2.0, 0.0, "static", "{}"], 
        ["cold_sweat:hoglin_headpiece", 0.0, 8.0, "static", "{}"], 
        ["cold_sweat:hoglin_tunic", 0.0, 12.0, "static", "{}"], 
        ["cold_sweat:hoglin_trousers", 0.0, 10.0, "static", "{}"], 
        ["cold_sweat:hoglin_hooves", 0.0, 8.0, "static", "{}"], 
        ["cold_sweat:goat_fur_cap", 8.0, 0.0, "static", "{}"], 
        ["cold_sweat:goat_fur_parka", 12.0, 0.0, "static", "{}"], 
        ["cold_sweat:goat_fur_pants", 10.0, 0.0, "static", "{}"], 
        ["cold_sweat:goat_fur_boots", 8.0, 0.0, "static", "{}"]
    ]
	#Defines the items that provide insulation when worn
	#See Insulation Ingredients for formatting
	"Insulating Armor" = [
        ["create:netherite_backtank"], 
        ["create:netherite_diving_helmet"], 
        ["create:netherite_diving_boots"], 
    #["minecraft:netherite_boots"], 
        ["minecraft:netherite_leggings"], 
        #alexsmobs
        ["alexsmobs:frontier_cap", 8.0, 0.0, "static", "{}"], 
        ["alexsmobs:fedora", 0.0, 8.0, "static", "{}"], 
        ["alexsmobs:roadrunner_boots", 0.0, 8.0, "static", "{}"], 
        ["alexsmobs:emu_leggings", 0.0, 10.0, "static", "{}"], 
        #butchercraft
        ["butchercraft:cow_hood", 4.0, 4.0, "static", "{}"], 
        ["butchercraft:goat_hood", 8.0, 0.0, "static", "{}"], 
        ["butchercraft:sheep_hood", 8.0, 0.0, "static", "{}"], 
        ["butchercraft:pig_hood", 0.0, 8.0, "static", "{}"], 
        #minecraft
        ["minecraft:leather_helmet", 4.0, 4.0, "static", "{}"], 
        ["minecraft:leather_chestplate", 6.0, 6.0, "static", "{}"], 
        ["minecraft:leather_leggings", 5.0, 5.0, "static", "{}"], 
        ["minecraft:leather_boots", 4.0, 4.0, "static", "{}"], 
        #cold_sweat
        ["cold_sweat:hoglin_headpiece", 0.0, 8.0, "static", "{}"], 
        ["cold_sweat:hoglin_tunic", 0.0, 12.0, "static", "{}"], 
        ["cold_sweat:hoglin_trousers", 0.0, 10.0, "static", "{}"], 
        ["cold_sweat:hoglin_hooves", 0.0, 8.0, "static", "{}"], 
        ["cold_sweat:goat_fur_cap", 8.0, 0.0, "static", "{}"], 
        ["cold_sweat:goat_fur_parka", 12.0, 0.0, "static", "{}"], 
        ["cold_sweat:goat_fur_pants", 10.0, 0.0, "static", "{}"], 
        ["cold_sweat:goat_fur_boots", 8.0, 0.0, "static", "{}"]
    ]
	#Defines the items that provide insulation when worn in a curio slot
	#See Insulation Ingredients for formatting
"Insulating Curios" = [
        # good against cold
        ["aether:leather_gloves",               4.0, 0.0, "static", "{}"],
        ["twilightaether:arctic_gloves",        4.0, 0.0, "static", "{}"],
        ["aether:gravitite_gloves",             4.0, 0.0, "static", "{}"],
        ["twilightaether:yeti_gloves",          4.0, 0.0, "static", "{}"],
        ["aether:neptune_gloves",               4.0, 0.0, "static", "{}"],
        ["aether:valkyrie_gloves",              4.0, 0.0, "static", "{}"],
        ["aether:valkyrie_cape",                6.0, 0.0, "static", "{}"],
        # good against hot
        ["cataclysm:sticky_gloves",             0.0, 4.0, "static", "{}"],
        ["aether:zanite_gloves",                0.0, 4.0, "static", "{}"],
        ["twilightaether:naga_gloves",          0.0, 4.0, "static", "{}"],
        ["twilightaether:fiery_gloves",         0.0, 4.0, "static", "{}"],
        ["aether:netherite_gloves",             0.0, 4.0, "static", "{}"],
        ["aether:phoenix_gloves",               0.0, 4.0, "static", "{}"],
        ["twilightaether:fiery_cape",           0.0, 6.0, "static", "{}"],
        # meh against both
        ["aether:iron_gloves",                  2.0, 2.0, "static", "{}"],
        ["aether:diamond_gloves",               2.0, 2.0, "static", "{}"],
        ["twilightaether:ironwood_gloves",      2.0, 2.0, "static", "{}"],
        ["twilightaether:knightmetal_gloves",   2.0, 2.0, "static", "{}"],
        ["aether:obsidian_gloves",              2.0, 2.0, "static", "{}"]
    ]
	#Defines how many insulation slots armor pieces have
	#There are 4 modes for this setting:
	#Static: Each armor slot (head, body, legs, feet) has a fixed number of insulation slots
	#- Format: [head, body, legs, feet] (a list of integers; insulation slot count for each armor slot)
	# 
	#Linear: Number of slots increases steadily with protection
	#Exponential: Number of slots increases rapidly with protection
	#Logarithmic: Number of slots increases with protection, with diminishing returns
	#- Format: [number, max-slots] (a positive integer or decimal; the rate of increase)
	"Insulation Slots" = ["static", 4, 6, 5, 4]
	#Defines the effectiveness of insulating items in protecting against temperature
	#Range: 0.0 ~ 1.7976931348623157E308
	"Insulation Strength" = 1.0
	#Defines wearable items that cannot be insulated
	#Format: ["item_id", "item_id", ...etc]
	"Insulation Blacklist" = []

[Consumables]
	#Defines items that affect the player's temperature when consumed
	#Format: [["item_id", amount, *nbt, *duration], ["item_id", amount, *nbt, *duration], ...etc]
	#Negative values are cold foods, positive values are hot foods
	#nbt: Optional. If set, the item will only affect the player's temperature if it has the specified NBT tag.
	#duration: Optional. If set, the player's temperature will remain increased/decreased for this amount of time (in ticks).
	"Temperature-Affecting Foods" = [
        ["cold_sweat:soul_sprout", -20.0, "{}", 1200]
    ]
	#Defines how much a waterskin will change the player's body temperature by when used
	#Range: > 0
	"Waterskin Strength" = 100 #default was 50
	#Determines the strength of the Soulspring Lamp's effect before it is overwhelmed
	#A value of 1 means it will never be overwhelmed
	#Range: 0.0 ~ 1.0
	"Soulspring Lamp Strength" = 0.8

[Misc]
	#Defines items that affect the player's temperature when in the inventory
	#Format: [["item_id", temperature, strict_type, trait, *nbt, *max_effect], ["item_id", temperature, strict_type, trait, *nbt, *max_effect], ...etc]
	#temperature: The temperature change the item will apply to the entity. For core temperature, this is applied every tick
	#strict_type: Either "inventory", "hotbar", or "hand". Defines what slots the item must be in to apply to the entity
	#trait: The temperature trait to apply the effect to. Typical values are "core" for body temperature or "world" for ambient temperature. More on the mod documentation page.
	#nbt: Optional. The NBT data the item must have to apply to the entity.
	#max_effect: Optional. The maximum temperature effect the item can apply to the entity.
	"Carried Item Temperatures" = []

